name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.0.0
        with:
          heroku_api_key: ${{secrets.HEROKU_SECRET_NM}}
          heroku_app_name: "Reto1NestorMorales"
          heroku_email: "HEROKU_EMAIL_NM"
          usedocker: true
